server.port=8080
spring.application.name=proyectodam-server

# MongoDB
spring.data.mongodb.uri=mongodb://localhost:27017/proyectodam

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/proyectodam_stats
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# JWT
app.jwt.secret=cGFzc3dvcmRfc2VjcmV0b19tX3NlZ3VyYV9wcm95ZWN0b0RBTTM=
app.jwt.expiration-ms=86400000

# CORS
app.cors.allowed-origins=http://localhost:4200

# Logging
logging.level.com.proyectodam=DEBUG